services:
  ananos-node:
    build: ./ananos-node
    volumes:
      - ananos_data:/root
    ports:
      # Communicating with other nodes
      - 0.0.0.0:7175:7175
      # HTTP RPC
      - 127.0.0.1:7176:7176
      # IPC RPC
      - 127.0.0.1:7177:7177
      # WS RPC
      - 127.0.0.1:7178:7178

volumes:
  ananos_data:
    driver: local