version: '3'

services:
  ananos-node:
    build: ./ananos-node
    volumes:
      - type: bind
        source: ./data
        target: /root/Ananos
        is_directory: true
    ports:
      # Communicating with other nodes
      - 0.0.0.0:7175:7175

  ananos-rpc-proxy:
    image: notthomiz/ananos-rpc-proxy:1.0.3
    environment:
      # For coolify to automatically give a port
      - SERVICE_FQDN_RPCPROXY_8080
    volumes:
      - type: bind
        source: ./proxy
        target: /data
        is_directory: true